import {
  FileText,
  AlertTriangle,
  CreditCard,
  Shield,
  Ban,
  Scale,
  Mail,
  MapPin,
  RefreshCw,
  Trash2,
} from "lucide-react";

const CONTACT_EMAIL = "hello@bbastian.dev";
const LAST_UPDATED = "6. Mai 2026";

interface Section {
  icon: React.ElementType;
  title: string;
  content: React.ReactNode;
}

export default function NouryTerms() {
  const sections: Section[] = [
    {
      icon: FileText,
      title: "Acceptance of terms",
      content: (
        <p className="text-left text-sm text-gray-400 leading-relaxed">
          By downloading, installing, or using the Noury app ("the Service"),
          you agree to be bound by these Terms of Service. If you do not agree,
          do not use the Service. These terms apply to all users of the app,
          including free and premium subscribers.
        </p>
      ),
    },
    {
      icon: AlertTriangle,
      title: "AI estimates — not medical advice",
      content: (
        <div className="space-y-3">
          <div className="flex gap-3 p-3 rounded-xl bg-yellow-500/5 border border-yellow-500/15">
            <AlertTriangle className="w-4 h-4 text-yellow-500 shrink-0 mt-0.5" />
            <p className="text-xs text-yellow-200/70 leading-relaxed text-left">
              All calorie, macro, and nutritional estimates generated by the AI
              (photo scan, voice log, recipe breakdown, AI coach) are{" "}
              <strong className="text-yellow-200/90">approximations only</strong>
              . They are not medical advice and should not replace guidance from
              a qualified nutritionist, dietitian, or physician.
            </p>
          </div>
          <ul className="space-y-2 text-sm text-gray-400 leading-relaxed">
            {[
              "AI-generated nutritional data may be inaccurate, incomplete, or out of date.",
              "Do not rely solely on Noury for managing medical conditions such as diabetes, eating disorders, or allergies.",
              "The developer accepts no liability for health decisions made based on data shown in the app.",
              "Always consult a qualified healthcare professional for medical or dietary advice.",
            ].map((item) => (
              <li key={item} className="text-left flex gap-2">
                <span className="text-yellow-500/70 mt-0.5 shrink-0">•</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>
      ),
    },
    {
      icon: CreditCard,
      title: "Subscriptions & billing",
      content: (
        <div className="space-y-3">
          <ul className="space-y-2 text-sm text-gray-400 leading-relaxed">
            {[
              "Noury offers a free tier and an optional Premium subscription. Premium features are clearly labelled within the app.",
              "Subscriptions are billed through Apple's in-app purchase system. Payment is charged to your Apple ID upon confirmation.",
              "Subscriptions automatically renew unless cancelled at least 24 hours before the end of the current billing period.",
              "You can manage or cancel your subscription at any time in your Apple ID account settings or in the App Store.",
              "No refunds are provided for partial subscription periods, except as required by applicable law (including mandatory EU consumer protection rights).",
              "Prices may change. You will be notified in advance of any price increase before your subscription renews.",
            ].map((item) => (
              <li key={item} className="text-left flex gap-2">
                <span className="text-emerald-500 mt-0.5 shrink-0">•</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
          <div className="p-3 rounded-xl bg-white/3 border border-white/8 text-left">
            <p className="text-xs font-semibold text-gray-400 mb-2">Required disclosure (Apple App Store)</p>
            <p className="text-xs text-gray-500 leading-relaxed">
              Subscription title, length, and price are shown in the app before purchase. By subscribing you confirm you have read and agree to our{" "}
              <a href="/noury/privacy" className="text-emerald-400 hover:underline underline-offset-2">Privacy Policy</a>
              {" "}and these Terms of Service. Cancel any time in <span className="text-gray-400">Settings → Apple ID → Subscriptions</span>.
            </p>
          </div>
        </div>
      ),
    },
    {
      icon: Shield,
      title: "Limitation of liability",
      content: (
        <div className="space-y-3">
          <p className="text-left text-sm text-gray-400 leading-relaxed">
            To the maximum extent permitted by applicable law:
          </p>
          <ul className="space-y-2 text-sm text-gray-400 leading-relaxed">
            {[
              'The Service is provided "as is" and "as available" without warranties of any kind, express or implied.',
              "The developer does not guarantee uninterrupted, error-free, or secure access to the Service.",
              "The developer is not liable for any indirect, incidental, special, or consequential damages arising from your use of or inability to use the Service.",
              "The developer is not responsible for the accuracy of data returned by third-party AI services (Google Gemini) or nutritional databases.",
              "Total liability in any case shall not exceed the amount you paid for the Service in the 12 months preceding the claim.",
            ].map((item) => (
              <li key={item} className="text-left flex gap-2">
                <span className="text-red-500/60 mt-0.5 shrink-0">•</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
          <p className="text-left text-xs text-gray-600 leading-relaxed pt-1">
            Nothing in these Terms limits or excludes liability where such
            limitation or exclusion is prohibited by applicable law, including
            mandatory consumer protection rights under Austrian or EU law.
          </p>
        </div>
      ),
    },
    {
      icon: Ban,
      title: "Acceptable use",
      content: (
        <div className="space-y-2">
          <p className="text-left text-sm text-gray-500 mb-3">
            You agree not to:
          </p>
          <ul className="space-y-2 text-sm text-gray-400 leading-relaxed">
            {[
              "Use the Service for any unlawful purpose or in violation of any applicable regulations.",
              "Attempt to reverse-engineer, decompile, or extract the source code of the app, except where expressly permitted by applicable law.",
              "Circumvent, disable, or interfere with security features or usage limits.",
              "Use the AI features to generate harmful, misleading, or dangerous content.",
              "Share your account credentials with others or create accounts on behalf of third parties.",
            ].map((item) => (
              <li key={item} className="text-left flex gap-2">
                <span className="text-red-500/60 mt-0.5 shrink-0">•</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>
      ),
    },
    {
      icon: Trash2,
      title: "Account deletion",
      content: (
        <div className="space-y-3">
          <p className="text-left text-sm text-gray-400 leading-relaxed">
            You may delete your account at any time directly within the app:
          </p>
          <ul className="space-y-2 text-sm text-gray-400 leading-relaxed">
            {[
              'Navigate to Settings → "Delete account" and follow the confirmation steps.',
              "Deletion is permanent. All personal data (meals, profile, health data) is erased within 30 days.",
              "Purchase records may be retained as required by applicable tax law (Austria: 7 years).",
              "If you are unable to access the app, contact us at hello@bbastian.dev to request deletion.",
            ].map((item) => (
              <li key={item} className="text-left flex gap-2">
                <span className="text-emerald-500 mt-0.5 shrink-0">•</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>
      ),
    },
    {
      icon: RefreshCw,
      title: "Service availability & changes",
      content: (
        <ul className="space-y-2 text-sm text-gray-400 leading-relaxed">
          {[
            "The developer reserves the right to modify, suspend, or discontinue the Service (or any part thereof) at any time.",
            "Features may be added, changed, or removed. Premium subscribers will be notified of material changes in advance.",
            "The developer is not liable for any loss resulting from modification or discontinuation of the Service.",
            "These terms may be updated at any time. Continued use of the app after an update constitutes acceptance of the revised terms.",
          ].map((item) => (
            <li key={item} className="text-left flex gap-2">
              <span className="text-emerald-500 mt-0.5 shrink-0">•</span>
              <span>{item}</span>
            </li>
          ))}
        </ul>
      ),
    },
    {
      icon: Scale,
      title: "Governing law",
      content: (
        <div className="space-y-3 text-sm text-gray-400 leading-relaxed text-left">
          <p>
            These Terms are governed by the laws of Austria. For any disputes
            arising from the use of the Service, Austrian courts have
            jurisdiction — however, this does not affect any mandatory
            consumer protection rights you may have under the law of your
            country of habitual residence.
          </p>
          <p>
            If you are a consumer resident in the EU, you retain the right to
            bring proceedings before the courts of your country of habitual
            residence, and any mandatory local consumer protection provisions
            that are more favourable to you apply regardless of this clause.
          </p>
          <p className="text-xs text-gray-600">
            EU consumers may also use the European Commission's Online Dispute
            Resolution platform:{" "}
            <span className="text-gray-500">ec.europa.eu/consumers/odr</span>
          </p>
        </div>
      ),
    },
    {
      icon: Mail,
      title: "Contact",
      content: (
        <div className="space-y-2">
          <p className="text-left text-sm text-gray-500 mb-3">
            Questions about these terms or the Service:
          </p>
          <div className="flex items-center gap-3 px-3 py-2.5 bg-white/3 border border-white/6 rounded-xl">
            <div className="w-7 h-7 rounded-lg bg-emerald-500/10 text-emerald-400 flex items-center justify-center shrink-0">
              <Shield className="w-3.5 h-3.5" />
            </div>
            <div>
              <p className="text-left text-xs text-gray-600 leading-none mb-0.5">
                Developer
              </p>
              <p className="text-sm font-medium text-white">Bastian</p>
            </div>
          </div>
          <div className="flex items-center gap-3 px-3 py-2.5 bg-white/3 border border-white/6 rounded-xl">
            <div className="w-7 h-7 rounded-lg bg-blue-500/10 text-blue-400 flex items-center justify-center shrink-0">
              <MapPin className="w-3.5 h-3.5" />
            </div>
            <div>
              <p className="text-xs text-gray-600 leading-none mb-0.5">
                Location
              </p>
              <p className="text-sm font-medium text-white">Austria</p>
            </div>
          </div>
          <a
            href={`mailto:${CONTACT_EMAIL}`}
            className="text-left flex items-center gap-3 px-3 py-2.5 bg-white/3 border border-white/6 rounded-xl hover:border-emerald-500/30 hover:bg-emerald-500/5 transition-all duration-150 group"
          >
            <div className="w-7 h-7 rounded-lg bg-emerald-500/10 text-emerald-400 flex items-center justify-center shrink-0">
              <Mail className="w-3.5 h-3.5" />
            </div>
            <div className="flex-1">
              <p className="text-xs text-gray-600 leading-none mb-0.5">
                Email
              </p>
              <p className="text-sm font-medium text-emerald-400 group-hover:underline underline-offset-2">
                {CONTACT_EMAIL}
              </p>
            </div>
          </a>
        </div>
      ),
    },
  ];

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white py-24 px-4">
      <div className="max-w-2xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-white/8 bg-white/4 text-xs text-gray-400 font-medium tracking-wide mb-5">
            <Scale className="w-3 h-3 text-emerald-400" />
            Noury · Terms of Service
          </div>
          <h1 className="text-4xl font-bold tracking-tight text-white mb-3">
            Terms of Service
          </h1>
          <p className="text-gray-500 text-sm leading-relaxed max-w-md mx-auto">
            The rules and limitations that apply when using the Noury app.
          </p>
          <p className="text-gray-700 text-xs mt-3">
            Last updated: {LAST_UPDATED}
          </p>
        </div>

        {/* Sections */}
        <div className="space-y-3">
          {sections.map(({ icon: Icon, title, content }) => (
            <div
              key={title}
              className="bg-[#111] border border-white/6 rounded-2xl p-5"
            >
              <div className="flex items-center gap-3 mb-3">
                <div className="w-8 h-8 rounded-lg flex items-center justify-center bg-emerald-500/10 text-emerald-400 shrink-0">
                  <Icon className="w-4 h-4" />
                </div>
                <h2 className="text-sm font-semibold text-white">{title}</h2>
              </div>
              {content}
            </div>
          ))}
        </div>

        {/* Bottom links */}
        <div className="flex items-center justify-center gap-4 mt-8">
          <a
            href="/noury/privacy"
            className="text-xs text-gray-600 hover:text-emerald-400 transition-colors"
          >
            Privacy Policy →
          </a>
          <span className="text-gray-800">·</span>
          <a
            href="/noury"
            className="text-xs text-gray-600 hover:text-gray-400 transition-colors"
          >
            Back to Noury
          </a>
        </div>
        <p className="text-center text-xs text-gray-700 mt-3">
          These terms apply to the Noury iOS app and{" "}
          <span className="text-gray-600">bbastian.dev/noury</span> and all
          related subpages.
        </p>
      </div>
    </div>
  );
}
